DROP TABLE  customers ;
DROP TABLE  employees ;
DROP TABLE  privileges ;
DROP TABLE  employee_privileges ;
DROP TABLE  inventory_transaction_types ;
DROP TABLE  shippers ;
DROP TABLE  orders_tax_status ;
DROP TABLE  orders_status;
DROP TABLE  orders;
DROP TABLE  products ;
DROP TABLE  purchase_order_status ;
DROP TABLE  suppliers;
DROP TABLE  purchase_orders;
DROP TABLE  inventory_transactions ;
DROP TABLE  invoices ;
DROP TABLE  order_details_status;
DROP TABLE  order_details ;
DROP TABLE  purchase_order_details;
DROP TABLE  sales_reports;
DROP TABLE  strings;
